cmsapp/urls.py
from django.conf.urls import url
from . import views

app_name ='cmsapp'

urlpatterns =[
    url(r'^(?P<slug>[^/]+)/delete$', views.delete, name='delete'),
    url(r'^$', views.index, name='index'),
    url(r'^:(?P<tag>[^/]+)/$', views.index, name='index'),
    url(r'^(?P<slug>[^/]+)/$', views.page, name='page'),
    url(r'^(?P<slug>[^/]+)/edit/$', views.change, name='change'),
    url(r'^\+$', views.change, name='change'),
]

cmsproject/urls.py
from django.conf.urls import url, include
from django.contrib import admin

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('cmsapp.urls')),
]

cmsapp/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from binascii import hexlify

from django.db import models
from os import urandom

def make_random_slug():
    return hexlify(urandom(6))

class Page(models.Model):
    def __repr__(self):  # https://pyformat.info/
        return "<Page #{0.pk} slug={0.slug!r} title={0.title!r}" \
               " content={0.content!r:.5}>".format(self)
    title = models.CharField(max_length=200)
    content = models.TextField()
    slug = models.SlugField(max_length=200, unique=True, default=make_random_slug)

class Tag(models.Model):
    name = models.CharField(max_length=200)
    page = models.ForeignKey("Page",
                             on_delete=models.CASCADE,
                             related_name='tags',
                             related_query_name='tag')

cmsapp/forms.py
from django import forms

from .models import Page, Tag


class TagField(forms.CharField):
    def clean(self, value):
        value = super(TagField, self).clean(value)
        tags = [item.strip() for item in value.split(',')]
        return [tag for tag in tags if tag]

class PageForm(forms.ModelForm):
    class Meta:
        model = Page
        fields = 'title', 'content', 'tags'

    def __init__(self, data=None, *, initial=None, instance=None, **kwargs):
        if instance:
            initial = initial or {}
            initial['tags'] = ', '.join(
                instance.tags.values_list('name', flat=True))
            print(initial['tags'])
        return super(PageForm, self).__init__(data, initial=initial, instance=instance,
                                              **kwargs)

    def save(self, commit=True):
        instance = super(PageForm, self).save(commit)
        if commit:
            self.instance.tags.all().delete()
            Tag.objects.bulk_create([
                Tag(name=tag, page=self.instance)
                for tag in self.cleaned_data['tags']
            ])
        return instance

    tags = TagField(required=False)

cmsapp/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.http import HttpResponseRedirect
from django.shortcuts import render, get_object_or_404, redirect, resolve_url

from .forms import PageForm
from .models import Page, Tag


# Create your views here.

def index(request, tag=None):
    if tag is None:
        pages = Page.objects.all()
    else:
        pages = Page.objects.filter(tag__name=tag)

    return render(request, "cmsapp/tem.html", {'pages': pages,
                                               'tags': Tag.objects.values('name').distinct(),})


def page(request, slug):
    page = get_object_or_404(Page, slug=slug)
    return render(request, "cmsapp/page.html", {
        'page': page,
        'tags': page.tags.all(),
    })

def delete(request, slug):
    instance = get_object_or_404(Page, slug=slug)

    if request.method == 'POST':
        instance.delete()
        return redirect('cmsapp:index')
    return render(request, 'cmsapp/delete.html', {
         'page': instance,
    })


# def add(request):
#     if request.method == 'POST':
#         form = PageForm(request.POST)
#         if form.is_valid():
#             obj = form.save()
#             return redirect('cmsapp:page', slug=obj.slug)
#     else:
#         form = PageForm()
#     return render(request, 'cmsapp/add.html', {
#         'form': form,
#     })


def change(request, slug=None):
    if slug is None:
        instance = None
    else:
        instance = get_object_or_404(Page, slug=slug)
    if request.method == "POST":
        form = PageForm(request.POST, instance=instance)
        if form.is_valid():
            instance = form.save()
            return redirect("cmsapp:page", slug=instance.slug)
    else:
        form = PageForm(instance=instance)
    return render(request, 'cmsapp/change.html', {
        'form': form, 'page': instance,
    })


# def edit(request, slug):
#     instance = get_object_or_404(Page, slug=slug)
#     if request.method == 'POST':
#         form = PageForm(request.POST, instance=instance)
#         if form.is_valid():
#             form.save()
#             return redirect('cmsapp:page', slug=instance.slug)
#     else:
#         form = PageForm(instance=instance)
#
#     return render(request, 'cmsapp/edit.html', {
#         'form': form,
#         'page': instance
#     })

cmsapp/templates/cmsapp/add.html
{% extends 'cmsapp/base.html' %}
{% block title %}[adding new pages] {% endblock %}
{% block body %}
    <form method="post" action="{% url 'cmsapp:add' %}">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <button type="submit">Save</button>
    </form>
{% endblock %}

cmsapp/templates/cmsapp/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>
        {% block title %} No title {% endblock %}
    </title>
</head>
<body>
    {% block body %}{% endblock %}
</body>
</html>

cmsapp/templates/cmsapp/change.html
{% extends 'cmsapp/base.html' %}
{% block title %}
    {% if page %}
        {{ page.title }} [editing]
    {% else %}
        [adding new page]
    {% endif %}
{% endblock %}

{% block body %}
    <form method="post" action="{% spaceless %}
        {% if page %}
            {% url 'cmsapp:change' page.slug %}
        {% else %}
            {% url 'cmsapp:change' %}
        {% endif %}{% endspaceless %}">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <button type="submit">Save</button>
    </form>
{% endblock %}

cmsapp/templates/cmsapp/delete.html
{% extends 'cmsapp/base.html' %}
{% block title %} {{ page.title }} [delete] {% endblock %}

{% block body %}
    <form method="post" action="{% url 'cmsapp:delete' page.slug %}">
        {% csrf_token %}
        <p>Are you sure you want to delete this page?</p>
        <button type="submit">Delete</button>
    </form>
{% endblock %}

cmsapp/templates/cmsapp/edit.html
{% extends 'cmsapp/base.html' %}
{% block title %} {{ page.tittle }} [editing] {%endblock %}

{% block body %}
    <form method="post" action="{% url 'cmsapp:edit' page.slug %}">
        {% csrf_token %}
        <table>{{ form.as_table }}</table>
        <button type="submit">Save</button>
    </form>
{% endblock %}

cmsapp/templates/cmsapp/includes/tags.html
{% if tags %}
<p>
    By tag:
    {% for tag in tags %}
    <a href="{% url 'cmsapp:index' tag.name %}">{{ tag.name }}
    </a>{% if not forloop.last %}, {% endif %}
    {% endfor %}
</p>
{% endif %}

cmsapp/templates/cmsapp/page.html
{% extends 'cmsapp/base.html' %}
{% block title %} Page: {{page.title}} {% endblock %}

{% block body %}
{% include "cmsapp/includes/tags.html" %}

<h1>{{page.title}} <a href="{% url 'cmsapp:change' page.slug %}">edit</a></h1>
{{ page.content }}

{% endblock %}

cmsapp/templates/cmsapp/tem.html
<!DOCTYPE html><body>
{% include "cmsapp/includes/tags.html" %}
<h1>Pages</h1>
<ul>
    {% for page in pages %}
    <li><a href="{% url 'cmsapp:page' page.slug %}">{{ page.title }}</a> </li>
    {% empty %}
    No pages yet!
    {% endfor %}
    <a href="{% url 'cmsapp:change' %}">Add another</a>
</ul></body></html>